//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// (Hand-written to match the kubebuilder layout so the project builds without
// running controller-gen; regenerate with `make manifests generate` once the
// kubebuilder toolchain is installed.)

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *FailoverApp) DeepCopyInto(out *FailoverApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *FailoverApp) DeepCopy() *FailoverApp {
	if in == nil {
		return nil
	}
	out := new(FailoverApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *FailoverApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *FailoverAppList) DeepCopyInto(out *FailoverAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		items := make([]FailoverApp, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&items[i])
		}
		out.Items = items
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *FailoverAppList) DeepCopy() *FailoverAppList {
	if in == nil {
		return nil
	}
	out := new(FailoverAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *FailoverAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *FailoverAppSpec) DeepCopyInto(out *FailoverAppSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *FailoverAppSpec) DeepCopy() *FailoverAppSpec {
	if in == nil {
		return nil
	}
	out := new(FailoverAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *FailoverAppStatus) DeepCopyInto(out *FailoverAppStatus) {
	*out = *in
	if in.Conditions != nil {
		conds := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&conds[i])
		}
		out.Conditions = conds
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *FailoverAppStatus) DeepCopy() *FailoverAppStatus {
	if in == nil {
		return nil
	}
	out := new(FailoverAppStatus)
	in.DeepCopyInto(out)
	return out
}
